### ISSUE TITLE
doesnt work on me

### ISSUE THREAD

**Issue by topraktxrk** [GaryOderNichts/udpih#10]
i follow like 20 tutorials to do this and still doesnt work so

1. i paste udpih.uf2 in the raspberry pico
2.i paste the recovery_menu into the sd card that is formated with fat32
3.i put the sd card in the wii u and i wait till the wii u starts to boot phiscly up or i wait till the wii u logo shows up 
4.then i put the pico with the udpih.uf2 file in the front usb slot
5.then the recovery menu shows up
6.i press on the  coldboot one with the power button and i chose eur
7. i now press the shutdown button in the menu then the wii u shuts down 
8. i unplug the pico cable and i boot up then the error shows up again i tried it even after the shutdown without the sd and both still in after the shutdown

i have a 160-0101  error not a 160-0103 

im not even sure that i put the udpih file right in bc after i put it in and i replug it with bootsel it doesnt show up 

i woulndt realy care about the wii u but im giving it to my sisters birthday its on the 12th april

**Comment by topraktxrk** [comment]
Please help only 3 days left

**Comment by GaryOderNichts** [comment]
This was most likely caused by corrupted system files and not a wrong coldboot title, if updating it doesn't change anything.
