### ISSUE TITLE
Support for x86_64 hosts

### ISSUE THREAD

**Issue by coatlessali** [GaryOderNichts/udpih#14]
Is it possible to build the kernel module for an x86 host? This would be useful in cases where ARM devices are unavailable.

**Comment by GaryOderNichts** [comment]
I don't think anything in the code is currently ARM specific? If you have a x86_64 host with a USB controller supporting USB device mode, feel free to give it a try.

**Comment by GaryOderNichts** [comment]
The latest release has been successfully tested on a Steam Deck, which is x86_64 and uses DWC3.
