### ISSUE TITLE
Pi Zero issues

### ISSUE THREAD

**Issue by Kayraman1** [GaryOderNichts/udpih#18]
I have everything preped but wont work .tries connecting pi to windows to see if its acknowledged as a usb device didnt see it anywere no pop ups nothing. tested the pi micro usb port --> works. tested kabel if its data --> yes . i really dont know why it wont work . can anyone help?

**Comment by Neverends4** [comment]
> ℹ️ To use USB gadgets on the Pi Zero you need to enable the dwc2 module by running the commands below:
echo "dtoverlay=dwc2" | sudo tee -a /boot/config.txt
echo "dwc2" | sudo tee -a /etc/modules
After running the commands reboot the system.

Have you finished these steps? Btw if you installed a newer OSlite on the zero, some steps need update, the file for new Pi-lite OS now is at:
`/boot/firmware/config.txt`
Edit and commented out the following:
```
#dtoverlay=vc4-kms-v3d
#max_framebuffers=2
```
Then add this line and reboot:
`dtoverlay=dwc2`

Also you need kernel injection after every reboot, remember. Just keep Zero powered on and use the 2nd cable to connect to Wii U.

**Comment by GaryOderNichts** [comment]
I updated the documentation for the Zero.
