### ISSUE TITLE
Error 3 using Switch - Method to correct problems on bricked WiiU

### ISSUE THREAD

**Issue by gautschh** [GaryOderNichts/udpih#2]
Dear Team! 

Thanks for this great piece of software!

Currently I got Error 3 within Switch Application, connected with bricked WiiU.

USB-C cable connected to Switch, other end to one of the front USB of the WiiU.

Please check this issue, error 3, thanks a lot, br Harald

**Comment by GaryOderNichts** [comment]
How are you launching the payload?
Are you plugging in the cable only once you can see the Wii U logo?
You can also try keeping the cable plugged in and only enter "Run UDPIH gadget" once you can see the Wii U logo.

**Comment by gautschh** [comment]
Thx for your fast response! Payload was injected by usb-c dongle from china and after that I tried windows program TegraRcmGUI with payload file from your github area.

There is no gamepad synced and the TV screen starts directly with WiiU Symbol. Maybe a timing issue from my side ? br Harald

**Comment by GaryOderNichts** [comment]
Can you test if the following build works?
[udpih_nxpayload.zip](https://github.com/GaryOderNichts/udpih/files/8864893/udpih_nxpayload.zip)

Also try using a different USB cable.

**Comment by gautschh** [comment]
Hello!

Thx for the new version.

I tried it with 2 cables (both one with data-connection), on 2 WiiU (one bricked, Error 160-0101, one working normal), I always get Error3.

I Updated Switch-Firmware too (used SXOS with EMUNand, Switch was on FW 8.0.1, within Emunand on 11.0) to 11.0 (real NAND) --> no difference, which Firmware do you use ?

Timing for USB-Connection ist after 2nd Drive-Seek (WiiU Logo appears some seconds after that).

I will try the rPi Zero Method now,, br Harald

**Comment by gautschh** [comment]
Hello, short feedback from my side.

Error 3 stays also on rPi Zero Method with temporary installed module (I´m no linux expert, maybe you can add some lines how to autoload the module ?), only the old rPi Zero without WLAN/BT should work or both of them ?

As I read on the other Issue there is a TV-Out (only) topic too, I have only the bricked WiiU without gamepad, so after Error 3 topic I have to wait for a new recovery_menu Version (I downloaded the testversion from Issue 3 here).

Thx again for your work, br Harald

**Comment by GaryOderNichts** [comment]
Where do you see "Error 3" on the Zero?
Also make sure to switch to dwc2 like described in #1.

Both Pi Zeroes work, I've been using the "W" version myself for testing.

**Comment by gautschh** [comment]
After adding dwc2 it works on 1st try (blind method without Gamepad), thx a lot for saving another bricked WiiU from Trash!!

Best regards, Harald

**Comment by gautschh** [comment]
Tiramisu works great too, have a nice (rest)weekend!
