### ISSUE TITLE
RPI4 instructions are ambiguous

### ISSUE THREAD

**Issue by DFXLuna** [GaryOderNichts/udpih#21]
Hi!

Trying to follow the setup guide with an RPI 4B and the instructions are ambiguous in a few places that makes it hard to tell exactly what to do. 

Do I leave the RPI4 on (and in the OS) with my other voltage source and plug it in during wiiu bootup? The line `For the Pi 4 and 5 you need to provide power through the power headers. Unfortunately the USB-C port handles both power and USB, and the Pi doesn't boot fast enough when plugged into the Wii U. You cannot use any of the USB-A ports in client mode.` makes it seem like either A) leave the RPI4 on and plug it in at the right time OR B) power on the RPI4 and plug it in at the same time. 

If I do A, the USB-A ports work without issue (tried with and without something plugged into the USB A ports).

However, the line `You need to insert the module again after rebooting the device.` makes it seem like B might be the correct plan.

Thoughts?

**Comment by GaryOderNichts** [comment]
You need to do `A) leave the RPI4 on and plug it in at the right time`.

`You need to insert the module again after rebooting the device.` refers to having to insert the module into the kernel again if you reboot the Pi, as the module doesn't get loaded on boot.

**Comment by DFXLuna** [comment]
Thanks for the quick reply! Would you mind if I PR'd the clarification to the docs?

**Comment by GaryOderNichts** [comment]
I don't mind. Documentation improvements are always welcome!
