### ISSUE TITLE
Adafruit Feather usb?

### ISSUE THREAD

**Issue by gaberilde** [GaryOderNichts/udpih#26]
It is RP2040 based, but i cant seem to get it working, not sure if i am doing anything wrong or the setup needs to be different for these?

**Comment by GaryOderNichts** [comment]
I'm not familiar with this board and I don't know if it's binary compatible with the Pico. Did you compile the project from source?

**Comment by gaberilde** [comment]
> I'm not familiar with this board and I don't know if it's binary compatible with the Pico. Did you compile the project from source?

No I haven't done it from source yet, you think I should try that?

**Comment by gaberilde** [comment]
Good news I managed to figure out how to build it from source and change it to feather rp2040 that I have now it's working perfectly, maybe you could add support for it in future builds?
