### ISSUE TITLE
WiiU (European) won't boot into recovery menu

### ISSUE THREAD

**Issue by Wuuzaaa** [GaryOderNichts/udpih#9]
Hi all, i'm having problems with getting into the recovery menu. I tried it with 3 different, all european models, WiiU's: a "160-0103" one (crashes after User Log-in), a working modded one and a working stock one. I am using the Pi Pico (non W). Tried re-flashing, updating via Thonny, different SD cards, different cables, tried different timings, both ports on the front, same outcome every time. My thoughts are either there is a problem with the region of the consoles or maybe the pico is faulty? If i plug the pico in too early the screen remains black and the console boot is interrupted. If i plug it in at the right timing (WiiU Logo popup) it boots normally into the user selection.

Did i miss something?

Thanks in advance for your help

Edit: Little update: tried with another pico and more sd cards, same results.

**Comment by Adamsapplespie** [comment]
I am getting the same issue with the recovery menu just not showing at all, and Im booting into the user selection menu. Maybe its just timing of the plug?

**Comment by Adamsapplespie** [comment]
Just to update this: Had to try a few more times but eventually got the timing right!

**Comment by GaryOderNichts** [comment]
Most likely wrong timing or unsupported firmware. Only 5.5.X is currently supported.
